name: Repository Dispatch File Creator

on:
  repository_dispatch:
    types: [hello_event]

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git Identity
        run: |
          git config --global user.name "Pavithran1508"
          git config --global user.email "pavithrang4@gmail.com"

      - name: Create file using client_payload
        run: |
          FILE_NAME="${{ github.event.client_payload.name }}.txt"
          echo "This file is created by a repository_dispatch event." > $FILE_NAME
          echo "Hello, ${{ github.event.client_payload.name }}!" >> $FILE_NAME
          git add $FILE_NAME
          git commit -m "Add $FILE_NAME"
          git push
